name: Sync Code to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  sync-to-bitbucket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clone Bitbucket repository
        run: |
          git clone https://ktooelazy@bitbucket.org/ktooelazy-adblock/adblock_auto.git -b main bitbucket
        working-directory: ./

      - name: Sync files to Bitbucket
        run: |
          rsync -av --delete Rules/ bitbucket/.
        working-directory: ./

      - name: Commit and push changes to Bitbucket
        run: |
          cd bitbucket
          git config --local user.email "${{ secrets.BITBUCKET_EMAIL }}"
          git config --local user.name "${{ secrets.BITBUCKET_NAME }}"
          git add .
          git commit -m "Sync Github changes"
          git push origin main
        working-directory: ./
