name: Sync Code to GITEA

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitea:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Git push assets to GITEA
        run: |
          git config --local user.name "${{ secrets.GITEA_NAME }}"
          git config --local user.email "${{ secrets.GITEA_EMAIL }}"
          git remote set-url --add origin "git@gitea.com:lonely_dog/adblock_auto.git"
          git checkout main
          git merge origin/main
          git add .
          git commit -a -m "update Rules"
          git branch -m main
          git push --force --set-upstream origin main
